# Generated by Django 4.1.7 on 2023-03-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='01-01-2023', verbose_name='Дата начала'),
        ),
    ]
