# Generated by Django 4.1.7 on 2023-03-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='issue_tracker.project', verbose_name='Проект'),
        ),
    ]
